name: GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  deployment:
    if: github.actor == 'gilbertrec'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: npm ci

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Generate sitemap
      run: python public/generate_sitemap.py

    - name: Commit sitemap.xml
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Update sitemap.xml" || echo "No changes to commit"
        git push
    - name: Build and Deploy
      env:
        NODE_ENV: production
        
        # This is set automatically by github
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/gilbertrec/gilbertrec.github.io.git
          npm run deploy
