name: Generate Sitemap

on:
  push:
    paths:
      - 'personal_doc/publications/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Generate sitemap
        run: |
          python generate_sitemap.py

      - name: Commit sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push
